from pymongo import MongoClient
import sqlite3

with MongoClient('mongodb://localhost:27017/') as mg_client, sqlite3.connect("../../data/imdb.db") as sql_conn:
    
    db = mg_client["imdb"]

    # Fetch tables from imdb.db
    tables = [i[0] for i in sql_conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()]

    # Filter out tables generated by sqlite
    tables = [i for i in tables if not "sqlite" in i]
    
    collections = db.list_collection_names()
    for t in tables:

        if t in collections: # Prevents reinserting existing data
            print("Collection " + t + " already exists, skipped")
            continue 

        # Fetch column names and types
        cols_infos = [(c[1], c[2]) for c in sql_conn.execute(f"PRAGMA table_info({t})").fetchall()]

        # Table values
        values = sql_conn.execute(f"SELECT * FROM {t}").fetchall()

        # convert to dicts for insertion, makes sure to correctly convert boolean fields
        docs = [
            {col_name: bool(v) if col_type == "BOOLEAN" else v for (col_name, col_type), v in zip(cols_infos, row)}
            for row in values
        ]

        db.create_collection(t)
        res = db[t].insert_many(docs)

        print("-----------Table " + t + "-----------")
        print("Entrées dans imdb.db: ", len(values))
        print("Documents créés : ", len(res.inserted_ids))
